version: "3.8"
services:
  app:
    build:
      context: ./app
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/db_data

volumes:
  db_data:
