version: "3.8"
services:
  app:
    ports:
      - 8000:8000
    env_file: .env.prod
    command: bash -c "chmod +x wait-for-db.sh
      && ./wait-for-db.sh
      && python manage.py makemigrations
      && python manage.py migrate --noinput
      && gunicorn src.wsgi:application --bind 0.0.0.0:8000"

  db:
    env_file: .env.prod
