# Generated by Django 3.2.5 on 2021-07-05 14:05

from django.db import migrations, models
import src.books.validators


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210705_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[src.books.validators.isbn_validator], verbose_name='ISBN'),
        ),
    ]
